name: test
run-name: testing
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-fish-shell
        run: |
          sudo apt-add-repository --yes --no-update ppa:fish-shell/release-3
          sudo apt-get update -qq
          sudo apt-get install --yes fish
        shell: bash
      - name: install-fisher-and-plugin
        run: |
          curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
          fisher install ./
        shell: fish {0}
      - name: run-test
        run: |
          fish ./test/test.fish
        shell: fish {0}
